Calkit CI: Retry dvc push if timeout, and commit numeric-results.tex

diff --git a/.github/workflows/calkit-run.yml b/.github/workflows/calkit-run.yml
--- a/.github/workflows/calkit-run.yml
+++ b/.github/workflows/calkit-run.yml
@@ -88,7 +88,13 @@ jobs:
           fi
 
           calkit dvc pull
-          calkit save dvc.lock dvc.yaml .calkit/ -m "Run pipeline"
+          calkit save dvc.lock dvc.yaml .calkit/ pubs/applied-ocean-research-model/numeric-results.tex pubs/renewable-energy-mdo/numeric-results.tex -m "Run pipeline"
+          PUSH_STATUS=$?
+
+          if [ $PUSH_STATUS -ne 0 ]; then
+            echo "Push failed, perhaps due to dvc push timeout. Retrying."
+            calkit dvc push
+          fi
       - run: |
           echo "Errors from latex:"
           grep -E "^!" pubs/applied-ocean-research-model/aux/main.log || true
