calkit workflow: add pull and branch before save to prevent losing results when refs diverge

diff --git a/.github/workflows/calkit-run.yml b/.github/workflows/calkit-run.yml
--- a/.github/workflows/calkit-run.yml
+++ b/.github/workflows/calkit-run.yml
@@ -35,6 +35,7 @@ jobs:
         run: |
           git config user.name github-actions[bot]
           git config user.email 41898282+github-actions[bot]@users.noreply.github.com
+          git remote set-url origin https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
       - name: Setup uv
         uses: astral-sh/setup-uv@v5
       - name: Install Calkit
@@ -69,10 +70,19 @@ jobs:
           dvc_token: ${{ secrets.CALKIT_DVC_TOKEN }}
           run_args: --ignore-errors --log
           save: false
-      - name: DVC push
+      - name: calkit save
         if: always()
         run: |
-          git remote set-url origin https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
+          set +e # Continue even if pull fails
+          calkit pull
+          PULL_STATUS=$?
+
+          if [ $PULL_STATUS -ne 0 ]; then
+            BRANCH="calkit-run-${{github.run_number}}-${{github.run_id}}"
+            echo "Pull failed due to merge conflict. Creating a new branch $BRANCH."
+            git checkout -b "$BRANCH"
+          fi
+
           calkit save dvc.lock dvc.yaml .calkit/ -m "Run pipeline"
       - if: ${{ always() && steps.run_calkit.outcome == 'failure' }}
         run: |
